import 'package:flutter/material.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';

ThemeData darkTheme = FlexThemeData.dark(
  scheme: FlexScheme.tealM3,
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
  blendLevel: 13,
  colorScheme: flexSchemeDark,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 20,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    alignedDropdown: true,
    useInputDecoratorThemeInDialogs: true,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
);

const ColorScheme flexSchemeDark = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xff53dbca),
  onPrimary: Color(0xff0a1413),
  primaryContainer: Color(0xff005048),
  onPrimaryContainer: Color(0xffdfeceb),
  secondary: Color(0xffaeccce),
  onSecondary: Color(0xff111414),
  secondaryContainer: Color(0xff304b4d),
  onSecondaryContainer: Color(0xffe7ebeb),
  tertiary: Color(0xffc0c3ef),
  onTertiary: Color(0xff131314),
  tertiaryContainer: Color(0xff404468),
  onTertiaryContainer: Color(0xffe9eaf0),
  error: Color(0xffffb4ab),
  onError: Color(0xff141211),
  errorContainer: Color(0xff93000a),
  onErrorContainer: Color(0xfff6dfe1),
  background: Color(0xff141b1a),
  onBackground: Color(0xffeceded),
  surface: Color(0xff141b1a),
  onSurface: Color(0xffeceded),
  surfaceVariant: Color(0xff354341),
  onSurfaceVariant: Color(0xffdfe1e1),
  outline: Color(0xff767d7d),
  outlineVariant: Color(0xff2c2e2e),
  shadow: Color(0xff000000),
  scrim: Color(0xff000000),
  inverseSurface: Color(0xfff6fdfc),
  onInverseSurface: Color(0xff131313),
  inversePrimary: Color(0xff326d65),
  surfaceTint: Color(0xff53dbca),
);
