import 'package:flutter/material.dart';
import 'package:flex_color_scheme/flex_color_scheme.dart';

ThemeData lightTheme = FlexThemeData.light(
  scheme: FlexScheme.tealM3,
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
  colorScheme: flexSchemeLight,
  blendLevel: 7,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 10,
    blendOnColors: false,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    alignedDropdown: true,
    useInputDecoratorThemeInDialogs: true,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
);

const ColorScheme flexSchemeLight = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xff006a60),
  onPrimary: Color(0xffffffff),
  primaryContainer: Color(0xffbbede6),
  onPrimaryContainer: Color(0xff101413),
  secondary: Color(0xff4a635f),
  onSecondary: Color(0xffffffff),
  secondaryContainer: Color(0xffcce8e2),
  onSecondaryContainer: Color(0xff111313),
  tertiary: Color(0xff48617a),
  onTertiary: Color(0xffffffff),
  tertiaryContainer: Color(0xffcfe5ff),
  onTertiaryContainer: Color(0xff111314),
  error: Color(0xffba1a1a),
  onError: Color(0xffffffff),
  errorContainer: Color(0xffffdad6),
  onErrorContainer: Color(0xff141212),
  background: Color(0xfff8fafa),
  onBackground: Color(0xff090909),
  surface: Color(0xfff8fafa),
  onSurface: Color(0xff090909),
  surfaceVariant: Color(0xffe0e6e6),
  onSurfaceVariant: Color(0xff111212),
  outline: Color(0xff7c7c7c),
  outlineVariant: Color(0xffc8c8c8),
  shadow: Color(0xff000000),
  scrim: Color(0xff000000),
  inverseSurface: Color(0xff101313),
  onInverseSurface: Color(0xfff5f5f5),
  inversePrimary: Color(0xff8ddcd5),
  surfaceTint: Color(0xff006a60),
);
