import 'package:flutter/material.dart';

ThemeData lightTheme = ThemeData(
    brightness: Brightness.light,
    appBarTheme: const AppBarTheme(backgroundColor: Colors.transparent),
    fontFamily: 'Roboto',
    colorScheme: const ColorScheme.light(
        primary: Color(0xFF6750A4),
        onPrimary: Color(0xFFFFFFFF),
        primaryContainer: Color(0xFFEADDFF),
        onPrimaryContainer: Color(0xFF21005D),
        secondary: Color(0xFF625B71),
        onSecondary: Color(0xFFFFFFFF),
        secondaryContainer: Color(0xFFE8DEF8),
        onSecondaryContainer: Color(0xFF1D192B),
        tertiary: Color(0xFF7D5260),
        onTertiary: Color(0xFFFFFFFF),
        tertiaryContainer: Color(0xFFFFD8E4),
        onTertiaryContainer: Color(0xFF31111D),
        error: Color(0xFFB3261E),
        onError: Color(0xFFFFFFFF),
        errorContainer: Color(0xFFF9DEDC),
        onErrorContainer: Color(0xFF410E0B),
        outline: Color(0xFF79747E),
        background: Color(0xFFFEF7FF),
        onBackground: Color(0xFF1D1B20),
        surface: Color(0xFFFEF7FF),
        onSurface: Color(0xFF1D1B20),
        surfaceVariant: Color(0xFFE7E0EC),
        onSurfaceVariant: Color(0xFF49454F),
        inverseSurface: Color(0xFF322F35),
        onInverseSurface: Color(0xFFF5EFF7),
        inversePrimary: Color(0xFFD0BCFF),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFF6750A4),
        outlineVariant: Color(0xFFCAC4D0),
        scrim: Color(0xFF000000),
    ),
    textTheme: const TextTheme(
        displayLarge: TextStyle(
            color: Colors.black,
            fontSize: 57,
            fontWeight: FontWeight.w400,
            height: 64/57,
        ),
        displayMedium: TextStyle(
            color: Colors.black,
            fontSize: 45,
            fontWeight: FontWeight.w400,
            height: 52/45,
        ),
        displaySmall: TextStyle(
            color: Colors.black,
            fontSize: 36,
            fontWeight: FontWeight.w400,
            height: 44/36,
        ),
        headlineLarge: TextStyle(
            color: Colors.black,
            fontSize: 32,
            fontWeight: FontWeight.w400,
            height: 40/32,
        ),
        headlineMedium: TextStyle(
            color: Colors.black,
            fontSize: 28,
            fontWeight: FontWeight.w400,
            height: 36/28,
        ),
        headlineSmall: TextStyle(
            color: Colors.black,
            fontSize: 24,
            fontWeight: FontWeight.w400,
            height: 32/24,
        ),
        titleLarge: TextStyle(
            color: Colors.black,
            fontSize: 22,
            fontWeight: FontWeight.w400,
            height: 28/22,
        ),
        titleMedium: TextStyle(
            color: Colors.black,
            fontSize: 16,
            fontWeight: FontWeight.w500,
            height: 24/16,
        ),
        titleSmall: TextStyle(
            color: Colors.black,
            fontSize: 14,
            fontWeight: FontWeight.w500,
            height: 20/14,
        ),
        bodyLarge: TextStyle(
            color: Colors.black,
            fontSize: 16,
            fontWeight: FontWeight.w400,
            height: 24/16,
        ),
        bodyMedium: TextStyle(
            color: Colors.black,
            fontSize: 14,
            fontWeight: FontWeight.w400,
            height: 20/14,
        ),
        bodySmall: TextStyle(
            color: Colors.black,
            fontSize: 12,
            fontWeight: FontWeight.w400,
            height: 16/12,
        ), 
        labelLarge: TextStyle(
            color: Colors.black,
            fontSize: 14,
            fontWeight: FontWeight.w500,
            height: 20/14,
        ),
        labelMedium: TextStyle(
            color: Colors.black,
            fontSize: 12,
            fontWeight: FontWeight.w500,
            height: 16/12,
        ),
        labelSmall: TextStyle(
            color: Colors.black,
            fontSize: 11,
            fontWeight: FontWeight.w500,
            height: 16/11,
        ),
        

    )
);